<?php

declare(strict_types=1);

namespace SistemAtc\Banks\Bradesco\DTO\Response\Cobranca;

use SistemAtc\Banks\Common\Attributes\JsonKey;
use SistemAtc\Banks\Common\Traits\AutoHydrate;
use SistemAtc\Banks\Common\Traits\CastToArray;
use SistemAtc\Banks\Contracts\DTOInterface;

/**
 * Boleto de cobrança convencional recém-registrado — espelha o
 * `BoletoResponseDTO` da spec (bloco 08 registro 1 e 2 do legado Bradesco).
 *
 * Valores monetários chegam como inteiro em CENTAVOS (`vlTitulo`, `vlJuros`…)
 * e datas como string `DD.MM.AAAA` ou inteiro `AAAAMMDD`, conforme o campo.
 *
 * Origem: POST /boleto/cobranca-registro/v1/cobranca
 */
final class BoletoRegistrado implements DTOInterface
{
    use AutoHydrate;
    use CastToArray;

    public function __construct(
        public readonly ?string $permPgtoParcial = null,
        public readonly ?int $cepComplementoSacadorAvalista = null,
        public readonly ?string $descCdMulta = null,
        public readonly ?string $status10 = null,
        public readonly ?string $tipoEndosso = null,
        public readonly ?int $despCart10 = null,
        public readonly ?string $numeroCartorio = null,
        public readonly ?string $dataSustacao = null,
        public readonly ?int $ctpoContrNegoc = null,
        public readonly ?string $descricacaoMoeda = null,
        public readonly ?int $tpVencimento = null,
        public readonly ?int $indicadorDecurso = null,
        public readonly ?string $dtVencimentoBoleto = null,
        public readonly ?string $dtDesconto1Bonificacao = null,
        public readonly ?int $vlJuros = null,
        public readonly ?string $aceite10 = null,
        public readonly ?int $tp08Reg2 = null,
        public readonly ?int $vlJurosAoDia = null,
        public readonly ?int $tp08Reg1 = null,
        public readonly ?string $enderecoSacadorAvalista = null,
        public readonly ?string $descEspecie = null,
        public readonly ?int $bcoCentr10 = null,
        public readonly ?int $negociacao = null,
        public readonly ?string $descCdDesconto2 = null,
        public readonly ?string $descCdDesconto3 = null,
        public readonly ?string $endEletronicoPagador = null,
        public readonly ?string $municipioPagador = null,
        public readonly ?int $acessEsc10 = null,
        public readonly ?int $cdJuros = null,
        public readonly ?int $contaDeb = null,
        public readonly ?int $vlAbatimento = null,
        public readonly ?string $bairroBeneficiario = null,
        public readonly ?int $vlTitulo = null,
        public readonly ?string $bairroPagador = null,
        public readonly ?int $qtdeCasasDecimaisDesconto3 = null,
        public readonly ?int $agenciaDeb = null,
        public readonly ?int $codStatus10 = null,
        public readonly ?string $especieDocumentoTitulo = null,
        public readonly ?int $agenOper10 = null,
        public readonly ?string $linhaDigitavel = null,
        public readonly ?int $dataImpressao10 = null,
        public readonly ?string $ufBeneficiario = null,
        public readonly ?string $ufPagador = null,
        public readonly ?int $cpfcnpjPagador = null,
        public readonly ?string $codigoOrigemTitulo = null,
        public readonly ?string $nomeBeneficiario = null,
        public readonly ?int $quantidadeMoeda = null,
        public readonly ?int $razaoContaDebito = null,
        #[JsonKey('diasInstrucaoProtestoNegativação')] public readonly ?int $diasInstrucaoProtestoNegativacao = null,
        public readonly ?int $cpssoaJuridContr = null,
        public readonly ?int $agenciaDebDv = null,
        public readonly ?string $dataPedidoSustacao = null,
        public readonly ?int $qtdeCasasDecimaisMulta = null,
        public readonly ?int $identTitDda10 = null,
        public readonly ?string $numeroProtocoloCartorio = null,
        public readonly ?int $bcoDepos10 = null,
        public readonly ?string $dtDesconto3 = null,
        public readonly ?int $ageCentr10 = null,
        public readonly ?string $dtDesconto2 = null,
        public readonly ?int $cdValorMulta = null,
        public readonly ?int $cdValorDesconto3 = null,
        public readonly ?int $cepComplementoBeneficiario = null,
        public readonly ?int $cdValorDesconto2 = null,
        public readonly ?string $nomeSacadorAvalista = null,
        public readonly ?int $diasDispensaMulta = null,
        public readonly ?string $dtVencimento = null,
        public readonly ?string $dtRegistro = null,
        public readonly ?string $indParcelaPrin10 = null,
        public readonly ?string $digCred10 = null,
        public readonly ?string $enderecoPagador = null,
        public readonly ?int $bancoDeb = null,
        public readonly ?int $idProduto = null,
        public readonly ?int $vlDesconto1Bonificacao = null,
        public readonly ?int $cepPagador = null,
        public readonly ?int $agenDepos10 = null,
        public readonly ?int $ctaCred10 = null,
        public readonly ?int $cense10 = null,
        public readonly ?int $razCredt10 = null,
        public readonly ?string $cepComplementoPagador = null,
        #[JsonKey('cpfcnpjBeneficiário')] public readonly ?string $cpfcnpjBeneficiario = null,
        public readonly ?string $ufSacadorAvalista = null,
        public readonly ?int $indInstrucaoProtesto = null,
        public readonly ?string $nuControleParticipante = null,
        public readonly ?int $vlTituloEmitidoBoleto = null,
        public readonly ?int $qtdePgtoParcial = null,
        public readonly ?int $horaImpressao10 = null,
        public readonly ?int $diasJuros = null,
        public readonly ?int $qtdeCasasDecimaisDesconto2 = null,
        public readonly ?int $cdValorDesconto1Bonificacao = null,
        public readonly ?int $cnpjCpfSacadorAvalista = null,
        public readonly ?string $seuNumeroTitulo = null,
        public readonly ?string $indBoletoDda10 = null,
        public readonly ?int $tpDesconto2 = null,
        public readonly ?int $tpDesconto1 = null,
        public readonly ?int $ctpoAbat10 = null,
        public readonly ?int $tpDesconto3 = null,
        public readonly ?string $indTitParceld10 = null,
        public readonly ?string $nuLogradouroBeneficiario = null,
        public readonly ?int $cepSacadorAvalista = null,
        public readonly ?string $descCdDesconto1Bonificacao = null,
        public readonly ?int $cprodtServcOper = null,
        public readonly ?string $codigoMoedaTitulo = null,
        public readonly ?int $vlDesconto3 = null,
        public readonly ?string $exibeLinDig10 = null,
        public readonly ?int $vlMulta = null,
        public readonly ?int $quantidadeCasas = null,
        public readonly ?string $municipioSacadorAvalista = null,
        public readonly ?int $vlDesconto2 = null,
        public readonly ?string $municipioBeneficiario = null,
        public readonly ?int $codigoOrigemProtesto = null,
        public readonly ?int $agencCred10 = null,
        public readonly ?int $quantidadeDiasDecurso = null,
        public readonly ?int $nuTituloGerado = null,
        public readonly ?int $cip10 = null,
        public readonly ?string $debitoAuto10 = null,
        public readonly ?int $cdValorJuros = null,
        public readonly ?string $dtEmissao = null,
        public readonly ?string $dtJuros = null,
        public readonly ?string $dtMulta = null,
        public readonly ?string $logradouroBeneficiario = null,
        public readonly ?int $vlIOF = null,
        public readonly ?string $cdBarras = null,
        public readonly ?string $cebp10 = null,
        public readonly ?int $diasDispensaJuros = null,
        public readonly ?int $qtdeCasasDecimaisDesconto1Bonificacao = null,
        public readonly ?int $cepBeneficiario = null,
        public readonly ?string $dataEnvioCartorio = null,
        public readonly ?string $nomePagador = null,
        public readonly ?string $complementoLogradouroBeneficiario = null,
        #[JsonKey('dtInstrucaoProtestoNegativação')] public readonly ?string $dtInstrucaoProtestoNegativacao = null,
        public readonly ?int $nseqContrNegoc = null,
        public readonly ?string $dtLimitePagamentoBoleto = null,
    ) {}
}
